### ISSUE TITLE
 Invalid bean definition with name / Cannot register bean definition

### ISSUE THREAD

**Issue by makampf** [miracum/kafka-fhir-to-server#50]
Folgender Fehler tritt im QS/Produktiv-Betrieb grundsätzlich auf. (Ich glaube aber nur dann, wenn mehrere Topics gemultiplext als Input angegeben werden)

```
2023-02-13 09:44:16.530 ERROR --- [   scheduling-1] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds

org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer:
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:528) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:103) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:144) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binding.BindingService.lambda$rescheduleConsumerBinding$1(BindingService.java:209) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-6.0.3.jar:6.0.3]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: org.springframework.beans.factory.support.BeanDefinitionOverrideException: Invalid bean definition with name 'kafka-718005357.sink-in-0.errors' defined in null: Cannot register bean definition [Root bean: class [org.springframework.messaging.SubscribableChannel]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null] for bean 'kafka-718005357.sink-in-0.errors' since there is already [Root bean: class [org.springframework.messaging.SubscribableChannel]; scope=; abstract=false; lazyInit=null; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodNames=null; destroyMethodNames=null] bound.
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.registerBeanDefinition(DefaultListableBeanFactory.java:1003) ~[spring-beans-6.0.3.jar:6.0.3]
	at org.springframework.context.support.GenericApplicationContext.registerBeanDefinition(GenericApplicationContext.java:350) ~[spring-context-6.0.3.jar:6.0.3]
	at org.springframework.context.support.GenericApplicationContext.registerBean(GenericApplicationContext.java:556) ~[spring-context-6.0.3.jar:6.0.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:773) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.registerErrorInfrastructure(AbstractMessageChannelBinder.java:705) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:716) ~[spring-cloud-stream-binder-kafka-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.kafka.KafkaMessageChannelBinder.createConsumerEndpoint(KafkaMessageChannelBinder.java:159) ~[spring-cloud-stream-binder-kafka-4.0.0.jar:4.0.0]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:474) ~[spring-cloud-stream-4.0.0.jar:4.0.0]
	... 10 common frames omitted
```

**Comment by chgl** [comment]
Könnte es https://github.com/spring-cloud/spring-cloud-stream/issues/2623 sein?

**Comment by makampf** [comment]
> Könnte es [spring-cloud/spring-cloud-stream#2623](https://github.com/spring-cloud/spring-cloud-stream/issues/2623) sein?

Definitiv.
